### ISSUE TITLE
Open to UI update?

### ISSUE THREAD

**Issue by kbknapp** [stratis-storage/stratis-storage.github.io#2]
I was having some issues reading the current color scheme of the how-to while at work which led to me doing a quick copy/paste into a Static Site Generator ([`zola`](https://github.com/getzola/zola)). If you're open to a new look I'd be more than happy to either transfer the repo to you, or open PR.

The site can be seen live at https://kbknapp.github.io/stratis-storage.github.io and the live site source can be seen on the [gh-pages branch](https://github.com/kbknapp/stratis-storage.github.io/tree/gh-pages)

Finally, the pre-generated source markdown files can be seen on the [master branch](https://github.com/kbknapp/stratis-storage.github.io)

**Comment by agrover** [comment]
Definitely. Looks really good, so much better. Things are a little complicated because the current site is actually generated from https://github.com/stratis-storage/stratis-docs, in order to generate PDFs from LyX documents and html from Markdown (except for index.html currently.) Do you think making the new design work with that repo is doable? (The site generation is one-time, right? Is this solely css and layout files that could be placed in to the docs repo's "website" directory?)

**Comment by kbknapp** [comment]
Excellent! Yeah it's just a single build step (`zola build`), which currently takes everything in the  `content/` dir in the form of Markdown files and spits out a fully functional static site in the `public/` dir. Static content, such as the PDF documents can live in the `static/` dir which doesn't see any transformation, and just gets spits verbatim into the output dir.

I'll take a look at the build steps of the `stratis-docs` repo and see if I can put the two together. I'm assuming it'll be pretty simple to merge them. All the building happens from the Makefile, correct?

**Comment by agrover** [comment]
yep, toplevel and then in each dir. Have at it. Thanks!

**Comment by mulkieran** [comment]
Closed by #118.
